[package]
name = "has_fields"
version = "0.1.0"
edition = "2021"
authors = ["lihe07"]
description = "A macro to check whether some fields are `Some` or not"
license = "Unlicense"
repository = "https://github.com/lihe07/has_fields"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"
